version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: [ "CMD-SHELL", "echo ruok | nc localhost 2181" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092" ]
      interval: 10s
      timeout: 10s
      retries: 10

  producer:
    build: ./producer
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC_RAW: raw-5g-data
      CSV_FILE: /app/data/Dashboard_data.csv
      STREAM_DELAY: "0.1"
    volumes:
      - ./data:/app/data:ro

  consumer:
    build: ./consumer
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC_RAW: raw-5g-data
      KAFKA_TOPIC_PREDICTIONS: predictions
      MODEL_PATH: /app/models/rf_optimized_binary.pkl
      MULTICLASS_MODEL_PATH: /app/models/rf_optimized_multiclass.pkl
      LABEL_ENCODER_PATH: /app/models/label_encoder_slice_type.pkl
      LABEL_ENCODER_ANOMALY_TYPE_PATH: /app/models/label_encoder_anomaly_type.pkl
    volumes:
      - ./models:/app/models:ro

  dashboard:
    build: ./dashboard
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8501:8501"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC_PREDICTIONS: predictions
